##Â **This code aims to separate between different df's all columns contained in the original OPTIONS dataset**

In [2]:
import pandas as pd
import os

In [8]:
project_dir = "/home/jupyter-tfg2425paula/prediction_project_v3"
os.chdir(project_dir)

raw_data_dir = os.path.join(project_dir, "00_data")
options_data_dir = os.path.join(raw_data_dir, "raw/options")

stocks = ['AAPL', 'MSFT', 'AMZN', 'NVDA', 'SPX']

In [9]:
df = pd.read_csv(os.path.join(options_data_dir, "combined_options.csv"))
df

,Date,AAPL_Close,AAPL_CALL_OM,AAPL_CALL_O1,AAPL_CALL_OY,AAPL_CALL_OI,AAPL_CALL_VM,AAPL_PUT_OM,AAPL_PUT_O1,AAPL_PUT_OY,...,SPX_CALL_OM,SPX_CALL_O1,SPX_CALL_OY,SPX_CALL_OI,SPX_CALL_VM,SPX_PUT_OM,SPX_PUT_O1,SPX_PUT_OY,SPX_PUT_OI,SPX_PUT_VM
0,2009-06-18,135.88,6.80,0.4063,0.4254,920448,31936.0,5.70,0.3943,0.4314,...,24.30,0.2568,0.2698,3816626,360148.0,28.16,0.2656,0.2939,5607238,468262.0
1,2009-06-19,139.48,5.40,0.3606,0.4244,687080,40040.0,5.96,0.3654,0.4145,...,23.00,0.2335,0.2635,3889631,211146.0,25.00,0.2524,0.2950,5775618,296620.0
2,2009-06-22,137.37,6.90,0.3852,0.4156,708547,25673.0,4.45,0.3845,0.4333,...,24.40,0.2880,0.2804,3806131,195176.0,26.90,0.2799,0.3056,5685968,312092.0
3,2009-06-23,134.01,4.52,0.3653,0.4180,725825,24184.0,5.60,0.3747,0.4259,...,24.00,0.2734,0.2752,3755289,117641.0,25.00,0.2757,0.3059,5287312,312995.0
4,2009-06-24,136.22,5.45,0.3513,0.4088,732078,16474.0,4.10,0.3464,0.4138,...,24.00,0.2707,0.2763,4028277,225367.0,22.60,0.2595,0.2936,6065984,255662.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4023,2024-11-19,228.28,6.15,0.2063,0.2470,2857385,75973.0,4.35,0.1891,0.2305,...,105.15,0.1320,0.1648,5931443,296301.0,77.60,0.1294,0.1589,9391154,403312.0
4024,2024-11-20,229.00,5.20,0.1999,0.2520,2868100,73730.0,5.17,0.1915,0.2328,...,106.20,0.1361,0.1658,5980482,186909.0,79.80,0.1345,0.1602,9494738,348931.0
4025,2024-11-21,228.52,6.30,0.2025,0.2522,2871366,77608.0,4.22,0.1941,0.2320,...,98.40,0.1307,0.1646,6034152,281112.0,78.65,0.1307,0.1596,9561087,406486.0
4026,2024-11-22,229.87,5.12,0.1876,0.2408,2889339,73138.0,4.35,0.2021,0.2289,...,86.00,0.1153,0.1615,6052109,143146.0,69.00,0.1168,0.1567,9654468,246708.0
4027,2024-11-25,232.87,5.16,0.1858,0.2439,203529,108236.0,3.85,0.1755,0.2243,...,84.00,0.1175,0.1549,2289360,169503.0,58.35,0.1100,0.1575,2250289,237586.0

In [10]:
for stock in stocks:
    # Select columns starting with the stock name plus the 'Date' column
    filtered_df = df[['Date'] + [col for col in df.columns if col.startswith(stock)]]

    # Define file name
    output_filename = f"{stock}_options.csv"

    # Save the filtered DataFrame
    filtered_df.to_csv(os.path.join(options_data_dir, output_filename), index=False)

    print(f"Saved {output_filename}")

Saved AAPL_options.csv
Saved MSFT_options.csv
Saved AMZN_options.csv
Saved NVDA_options.csv
Saved SPX_options.csv

In [ ]:
data_dir = os.path.join(project_dir, "00_data")
horizontal_data_dir = os.path.join(data_dir, "horizontal_structure")

types_data = ["pca", "raw"]
types_securities = ["single_name", "options", "technical"]
stocks = ['AAPL', 'MSFT', 'AMZN', 'NVDA', 'SPX']
years = ["15y", "10y", "5y", "2Y"]